apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-api-config
  namespace: fcg
data:
  ASPNETCORE_URLS: http://+:8080
  RabbitMq__Host: rabbitmq
  RabbitMq__UserQueue: notifications-users
  RabbitMq__PaymentQueue: notifications-payments
