apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
  namespace: fcg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
        - name: notifications-api
          image: fcg/notifications-api:cors-v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: notifications-api-config
            - secretRef:
                name: fcg-secrets
          env:
            - name: ConnectionStrings__Database
              valueFrom:
                secretKeyRef:
                  name: fcg-secrets
                  key: NotificationsDatabase
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
